games/urls.py
from django.conf.urls import url

from . import views

app_name = 'games'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

yiying/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from games import views



urlpatterns = [
    url(r'^$', include('games.urls')),
    url(r'^(?P<game_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^summary/$', views.summary, name='summary'),
    url('admin/', admin.site.urls),
    
]

games/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class History(models.Model):
    def __str__(self):
        return self.player_name + " : " + self.game_name

    player_name = models.CharField(max_length=200)
    game_name = models.CharField(max_length=200)
    comment = models.TextField()
    played_time = models.DateTimeField('time played')

games/forms.py
from django import forms
from .models import History

class GameForm(forms.ModelForm):
    player_name = forms.CharField(min_length=1, max_length=200)
    comment = forms.CharField(
                            widget=forms.Textarea(
                                attrs={'rows':5, 'placeholder': 'What is on your mind?'}
                            ),
                            min_length=1, 
                            max_length=4000)  # TODO: this placeholder is not working.

    class Meta:
        model = History
        fields = ['player_name', 'comment']

games/views.py
from django.shortcuts import HttpResponse, render, redirect
from django.views import generic
from django.urls import reverse
from .forms import GameForm
from .models import History
from datetime import datetime
import requests

# Create your views here.
def index(request):
    return render(request, 'games/home.html', {})

def detail(request, game_id):
    game_map = {'0': "Connect4Game", '1': "Number Game"}
    if request.method == "GET":
        if game_id == '0' or game_id == '1':
            return render(request, 'games/game.html', {"game_id": game_id})
        elif game_id == '2':
            response = requests.get('http://freegeoip.net/json/')
            geodata = response.json()
            return render(request, 'games/map.html', {
                'time zone': geodata['time_zone'],
                'country': geodata['country_name'],
                'latitude': geodata['latitude'],
                'longitude': geodata['longitude'],
                'api_key': "AIzaSyDJDxy3ex0Y0FByMHmmMEOp5lI0FWmUZvY"
            })
        else:
            return render(request, 'games/developing.html', {})
    elif request.method == "POST":
        form = GameForm(request.POST)
        if form.is_valid():
            record = form.save(commit=False)
            player_name = record.player_name
            game_name = game_map[game_id]
            comment = record.comment
            played_time = datetime.now()
            history = History.objects.create(
                player_name = player_name,
                game_name = game_name,
                comment = comment,
                played_time = played_time
            )
            return redirect(reverse('summary'))
        else:
            form = GameForm()
        return render(request, 'games/game.html', {"game_id": game_id})

def summary(request):
    records = History.objects.all()
    return render(request, 'games/summary.html', {"records": records})

games/templates/games/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Yiying's Game App</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>


    <!-- Custom styles for this template -->
    <link href="{% static 'games/css/carousel.css' %}" rel="stylesheet">

    <!-- REACT inclusion -->
    <meta charset="UTF-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.21.1/babel.min.js"></script>


  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <header>
      <div class="navbar-wrapper">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'games:index' %}" class="color-me1">Home</a>
              <li><a href="#" class="color-me2">Log In</a></li>
              <li><a href="#" class="color-me2">Sign Up</a></li>
            </ul>
        </div>
      </div>
    </header>
    <main>
    <div class="container-fluid">
      {% block index %}
      {% endblock %}
    </div>

    <div id="game" class="container-fluid">
      {% block content %}
      {% endblock %}
    </div>

    </main>
  
    <div class="container" style="margin-top: 10px;">
        <footer>
          <p>&copy; 2018 Yiying, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
          <p class="pull-right"><a href="">Back to top</a></p>
        </footer>
    </div>

  </body>
 
</html>

games/templates/games/developing.html
{% extends 'games/base.html' %}

{% block content %}
	<h1>This game is still under development</h1>
{% endblock %}

games/templates/games/game.html
{% extends 'games/base.html' %}

{% block content %}
	<body>
         <div id="root">
	         <script>
	         	var game_page = '../../static/games/js/game_' + {{ game_id }} +'.jsx'
	         	document.write("<scr" + "ipt type='text/jsx' src=" + game_page + "></sc" + "ript>");
	         </script>
         </div> 
	</body>

{% endblock %}

games/templates/games/home.html
{% extends 'games/base.html' %}
{% load staticfiles %}

{% block index %}
<!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
<body>
    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'games/images/connect-4-game.jpg' %}" alt="Generic placeholder image">
          <h2 style="padding-top: 50px;">Connect 4 Game</h2>
          <p>This game is centuries old, Captain James Cook used to play it with his fellow officers on his long voyages, and so it has also been called "Captain's Mistress". Milton Bradley (now owned by Hasbro) published a version of this game called "Connect Four" in 1974.</p>
          <p><a class="btn btn-default" href="0" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'games/images/number-game.jpg' %}" alt="Generic placeholder image">
          <h2 style="padding-top: 50px;">Math Game</h2>
          <p>Math is wholly unhindered and remarkably unaffected by language, race, religion or other cultural factors. It is an incredible, universal language of concepts that can be taught and understood regardless of where you are or what you believe.</p>
          <p><a class="btn btn-default" href="1" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'games/images/map-game.jpg' %}" alt="Generic placeholder image">
          <h2 style="padding-top: 50px;">Where You Are</h2>
          <p>Perhaps to lose a sense of where you are implies the danger of losing a sense of who you are. I thought—to lose your direction is to lose your face. So here he comes to ask his direction from the lost, the invisible. Very well, I’ve learned to live without direction.</p>
          <p><a class="btn btn-default" href="2" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->

     </div>
</body>
    
{% endblock %}

games/templates/games/map.html
{% extends 'games/base.html' %}

{% block content %}
  <div style="justify-content:center;">
	  <h3>I guess, you are probably in <strong>{{ country }}</strong> right now.</h3>
	  <iframe width="600"
	          height="450"
	          frameborder="0"
	          style="border:0"
	          src="https://www.google.com/maps/embed/v1/view?center={{ latitude }},{{ longitude }}&zoom=8&key={{ api_key }}"
	          allowfullscreen></iframe>
   </div>

{% endblock %}

games/templates/games/summary.html
{% extends 'games/base.html' %}


{% block summary %}
<style>
	table {
	    border-collapse: collapse;
	    background-color: yellow;
        width:100%;
        margin-right:auto;
        margin-left:auto;
	}

	th, td {
	    text-align: center;
	    padding: 8px;
	}
	th {
		background-color: lightblue;
	}
	tr:nth-child(even){background-color: #f2f2f2}
</style>
<div class="container" style="width:90%;">
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Player Name</th>
        <th>Game Name</th>
        <th>Comments</th>
        <th>Played Time</th>
      </tr>
    </thead>
    <tbody>
    	{% for record in records %}
    		<tr>
    			<td>{{ record.player_name }}</td>
    			<td>{{ record.game_name }}</td>
    			<td>{{ record.comment }}</td>
    			<td>{{ record.played_time }}</td>
    		</tr>
    	{% endfor %}
    </tbody>
  </table>
  <div class="mb-4" style="padding-top: 100px;">
    <a href="{% url 'games:index' %}" class="btn btn-primary">Back to Menu</a>
  </div>
 </div>


{% endblock %}